version: "2"
services:
  nodejs-mentoring: 
    image: staptala/nodejs-mentoring
    ports: 
      - 80:8080
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:123@localhost:5432/homework06
      - PORT=8080
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=homework06